cargo-features = ["codegen-backend"]

[workspace]
members = [
	"v_utils",
	"v_utils_*",
]
resolver = "1"

[workspace.dependencies]
eyre = { version = "0.6.12" } # not color-eyre, that one is for client-side
serde = { version = "1.0.215", features = ["derive"] }
